### ISSUE TITLE
Vextorized query error 

### ISSUE THREAD

**Issue by kirankumarduddu** [pamelafox/vector-search-demos#1]
Traceback (most recent call last):
  File "c:\Visual Code\track1-local\test-vector-search.py", line 5, in <module>
    from azure.search.documents.indexes.models import VectorizedQuery
ImportError: cannot import name 'VectorizedQuery' from 'azure.search.documents.indexes.models' (C:\Users\KiranDuddu\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\search\documents\indexes\models\__init__.py)
 although Successfully installed azure-search-documents-11.4.0 is installed

**Comment by pamelafox** [comment]
I can't replicate the error, are you working inside a dev container or virtual env to make sure you're using the correct packages?

**Comment by pamelafox** [comment]
Closing since I cant replicate. Please try in GitHub Codespaces.
